### ISSUE TITLE
Unescape caracters on Windows

### ISSUE THREAD

**Issue by rouabhi** [ismnoiet/BowerInjector#4]
On windows platform, characters should be unescaped.
Indeed, when you generate for instance a path with "d:\bower" the "\b" is interpreted as a BS (ASCII 7) character. All back slash characters "\" should be doubled "\".

**Comment by ismnoiet** [comment]
I'll try it with double backslashes for windows, thank you :)

**Comment by rouabhi** [comment]
In fact, you should instead use the same format as Unix platform, with a relative path:
"./bowser_components/stream/stream.js"

**Comment by ismnoiet** [comment]
Oops i forgot about that, indeed windows is something "**weird**" compared to linux-based OS.
Problem solved.
